modified all conditional statements

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -59,23 +59,23 @@ jobs:
         VARIABLE=ABC
         echo $VARIABLE
         export ACTION_ID=${{github.action}}
-        ls
+        l
       continue-on-error: true
         
     - name: Status for Push to ECR
       id: failStep
-      if: always() && ${{ steps.PushToECR.outcome }} == 'failure'
+      if: always() && ${{ steps.PushToECR.outcome == 'failure' }} 
       uses: ouzi-dev/commit-status-updater@v1.1.0
       with:
         status: "failure"
         url: "https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}?check_suite_focus=true"
         description: "this is my status check"
         name: "Push to ECR"
-    - if: ${{ steps.PushToECR.outcome == 'failure' }} 
-      run: exit 1
-      shell: bash
+    #- if: ${{ steps.PushToECR.outcome == 'failure' }} 
+     # run: exit 1
+      #shell: bash
     - name: Status for Push to ECR 
-      if: always() && ${{ steps.PushToECR.outcome }} == 'success'
+      if: always() && ${{ steps.PushToECR.outcome == 'success' }} 
       uses: ouzi-dev/commit-status-updater@v1.1.0
       with:
         status: "success"
