testing without condition

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -16,10 +16,10 @@ jobs:
       
     - name: run script
       run: |
-        chmod 777 $GITHUB_WORKSPACE/.github/workflows/test.sh
-        $GIRHUB_WORKSPACE/.github/workflows/test.sh
-        if [ $? -eq 0 ]; then
-          echo "success"
-        else
-          echo "fail"
-        fi
+        chmod 777 ./.github/workflows/test.sh
+        ./.github/workflows/test.sh
+      #  if [ $? -eq 0 ]; then
+       #   echo "success"
+      #  else
+      #    echo "fail"
+      #  fi
